name: Deploy Streamlit on EC2 (Auto Restart)

on:
  push:
    paths:
      - 'streamlit-app/**'
      - '.github/workflows/deploy-streamlit.yml'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd streamlit-app
          pip install -r requirements.txt

      - name: Stop Old Streamlit Process
        run: |
          pkill -f "streamlit run" || echo "✅ No old streamlit running"

      - name: Start Streamlit App in Background
        run: |
          cd streamlit-app
          nohup streamlit run app.py --server.address 0.0.0.0 --server.port 8501 > ~/streamlit.log 2>&1 &
          echo "✅ Streamlit restarted on port 8501"
